version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:10.4-alpine
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
      