version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:10.4-alpine
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: postgres-test
      POSTGRES_USER: pgtest
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
networks:
  default:
    external:
      name: docker-graphql